sudo: false
language: ruby
rvm:
  - 2.4.3
env:
  global:
    - PGPORT=5433
addons:
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  postgresql: 10
before_install: gem install bundler -v 1.16.2
before_script:
  - cp database.yml.travis test/dummy/config/database.yml
  - psql -c 'create database delayed_henka_test;' -U postgres
  - RAILS_ENV=test bundle exec rails db:migrate
script:
  - bundle exec rspec
